# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

removeAdapter <- function(argvs) {
    .Call('atacpipe_removeAdapter', PACKAGE = 'atacpipe', argvs)
}

renamer <- function(argvs) {
    .Call('atacpipe_renamer', PACKAGE = 'atacpipe', argvs)
}

bowtie2Mapping <- function(argvs) {
    .Call('atacpipe_bowtie2Mapping', PACKAGE = 'atacpipe', argvs)
}

bowtie2Build <- function(argvs) {
    .Call('atacpipe_bowtie2Build', PACKAGE = 'atacpipe', argvs)
}

R_sam2bed_wrapper <- function(argvs) {
    .Call('atacpipe_R_sam2bed_wrapper', PACKAGE = 'atacpipe', argvs)
}

